#%RAML 1.0 DataType
properties:
  hotelId: number
  hotelName: string
  hotelLocation: string
  numberOfRoomwithoutAc: integer
  numberOfRoomwithAc: integer
  Aminities: 
  Auditorium: string 
  playGround: string 
  swimingPool: string
  hotelAddress: 
  address: string
  pinCode: string
  state: string
  district: string
  country: string
  googleMapUrl: string
  contactNumber: string
  mailAddress: string
  contactPerson: string